language: minimal

cache:
  directories:
    - $HOME/.cache/Tectonic

before_install:
  # Download and install conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r

    # Install tectonic
  - conda install -y -c conda-forge tectonic==0.1.11
  - conda install -y -c malramsay biber==2.11

script:
  - tectonic research_report/research_report.tex

deploy:
  provider: releases
  api_key: 04c018ac80e14317a5c1a364c20deeb6f7ee09ab
  file: research_report.pdf
  skip_cleanup: true
